version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: seller-department-postgres
    environment:
      POSTGRES_DB: sellerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seller123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: seller-department-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sellerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: seller123
      JWT_SECRET: aoh5roHVw4IbQqD1K8ksQRxjVRybbkbuDvWVDDi4MZQ=
    depends_on:
      - postgres

volumes:
  postgres_data: